### ISSUE TITLE
magnet link

### ISSUE THREAD

**Issue by gilgamezh** [codenirvana/kTorrent#1]
Can you add the magnet link in the results?

I'm looking to use your lib here https://github.com/touchandgo-devs/touchandgo

Maybe you can solve the "download" issue with it :wink:

**Comment by codenirvana** [comment]
@gilgamezh Sure I will :+1:

**Comment by codenirvana** [comment]
@gilgamezh magnet link added!

**Comment by gilgamezh** [comment]
thanks! more news coming soon :)
